### ISSUE TITLE
Execute standalone TopoFlow component outside of WMT

### ISSUE THREAD

**Issue by mdpiper** [csdms/component_metadata#19]
The goal is to run a TopoFlow component (or, preferably, a few components) in Python so that we better understand how to set up and call them in WMT.

**Comment by mdpiper** [comment]
From a cursory attempt, this was harder than I thought it would be.

**Comment by mperignon** [comment]
Is this still an open issue? It was assigned to me and I've been awfully neglectful...
I'm assuming this would all be happening outside of WMT, using the individual Topoflow Python files.

Otherwise, I'm going to start working on the metadata for STM.

**Comment by mperignon** [comment]
I finally managed to get this to work. The only way to run topoflow outside of WMT is to go through topoflow.frameworks.emeli , which checks that all of the components needed to supply the _input_var_names for the driver (and each other) are there. It doesn't matter if a component is disabled and not actually providing anything. It still needs to have the input files and be initialized. So it won't run without being coupled with gc2d even if there are no glaciers.

There are also some components with issues that I can't explain. With time_interp_method = 'linear', self.P_rain is type np.array during initialization and type None during update, but I can't find where it gets cleared. Similarly, channels_diffusive_wave has a self.S_free but channels_base says it doesn't exist (but it works with channels_kinematic_wave).

I'm going to check every component flavor (channels kinematic, diffusive...) and set aside the ones with weird issues for now. Then I'll strip down the python scripts to make the simplest possible combination of modules that still runs and build back up from there.

Does that sound reasonable?

I am thinking that the components of topoflow will never be able to couple to other models if they demand that all kinds of weird variables exist even if they do nothing - for example, channels_base.py looks for 

    _input_var_names = [
        'atmosphere_water__rainfall_volume_flux',          # (P_rain)
        'glacier_ice__melt_volume_flux',                   # (MR)
        'land_surface_water__baseflow_volume_flux',        # (GW)
        'land_surface_water__evaporation_volume_flux',     # (ET)
        'soil_surface_water__infiltration_volume_flux',    # (IN)
        'snowpack__melt_volume_flux',                      # (SM)
        'water-liquid__mass-per-volume_density' ]           # (rho_H2O)     

Those should instead be in two separate lists: P_rain, which it actually requires, and the rest, which it can set to zero or look up on a table (rho_H2O, for example). Also, the baseflow volume flux and evaporation volume flux might not have to come from the same model component, but the way we are building the uses.json and provides.json now, they do. I'm not sure how to go around that.
